todo-aspnetmvc/Controllers/ItemsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using todo_aspnetmvc.Services;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Controllers
{
    [Route("[controller]/[action]")]
    public class ItemsController : Controller
    {
        private readonly IItemService _itemsService;

        public ItemsController(IItemService itemsService)
        {
            _itemsService = itemsService;
        }


        public async Task<IActionResult> EditItem(Guid? taskId, Guid? listId)
        {
            if (taskId.HasValue)
            {
                var task = await _itemsService.GetItem(taskId.Value);
                return View(task);
            }

            return View(new ItemModel{ToDoListId = listId.Value});
        }

        [HttpPost]
        public async Task<IActionResult> SaveTask([FromForm] ItemModel task)
        {
            if (!ModelState.IsValid)
            {
                return View("EditItem", task);
            }
            
            if (task.Id == Guid.Empty)
            {
                task.Id = await _itemsService.Create(task);
                return RedirectToAction("Get", "ToDoList", new {listId = task.ToDoListId});

            }

            var taskEntity = await _itemsService.GetItem(task.Id);
            taskEntity.Name = task.Name;
            taskEntity.Description = task.Description;
            taskEntity.CompletionDate = task.CompletionDate;

            await _itemsService.Update(taskEntity);
            return RedirectToAction("Get", "ToDoList", new {listId = taskEntity.ToDoListId});
        }

     
      
        [HttpPost("{taskId:guid}")]
        public async Task<IActionResult> UpdateStatus([FromRoute] Guid taskId, [FromForm] UpdateTaskModel model)
        {
            await _itemsService.UpdateStatus(taskId, model.Status);
            return Ok();
        }

        
        /// <summary>
        /// Method deletes task by Id
        /// </summary>
        /// <param name="taskId"></param>
        /// <returns></returns>
        [HttpPost("{taskId:guid}")]
        public async Task<IActionResult> DeleteTask([FromRoute] Guid taskId)
        {
            var task = await _itemsService.GetItem(taskId);
            await _itemsService.Delete(taskId);
            return RedirectToAction("Get", "ToDoList", new {listId = task.ToDoListId});
        }
    }
}

todo-aspnetmvc/Controllers/ToDoListController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using todo_aspnetmvc.Services;
using todo_domain_entities.Models;

namespace todo_aspnetmvc.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly IToDoListService _toDoListsService;

        public ToDoListController(IToDoListService toDoListsService)
        {
            _toDoListsService = toDoListsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(bool isHidden = false)
        {
            var toDoList = await _toDoListsService.GetToDoLists(new ItemFilterParameters {IsHidden = isHidden});

            return View(toDoList);
        }


        [HttpGet("{listId:guid}")]
        public async Task<IActionResult> Get([FromRoute] Guid listId)
        {
            ToDoListModel findTask = await _toDoListsService.GetToDoList(listId);
            return View(findTask);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? listId)
        {
            if (listId.HasValue)
            {
                ToDoListModel findTask = await _toDoListsService.GetToDoList(listId.Value);
                return View(findTask);
            }

            return View(new ToDoListModel());
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromForm] ToDoListModel list)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", list);
            }
            
            if (list.Id == Guid.Empty)
            {
                list.Id = await _toDoListsService.Create(list);
            }
            else
            {
                await _toDoListsService.Update(list.Id, list);
            }

            return RedirectToAction("Get", "ToDoList", new {listId = list.Id});
        }

        [HttpPost("{listId:guid}")]
        public async Task<IActionResult> DeleteList([FromRoute] Guid listId)
        {
            await _toDoListsService.Delete(listId);
            return RedirectToAction("Index", "ToDoList");
        }
    }
}

todo-aspnetmvc/Views/Items/EditItem.cshtml
@model todo_domain_entities.Models.ItemModel

@{
    @if (@Model.Id == Guid.Empty)
    {
        ViewBag.Title = "Add task";}
    else
    {
        ViewBag.Title = "Edit task";}
    Layout = "_Layout";
}

@using (Html.BeginForm("SaveTask", "Items", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.ToDoListId)
    <div class="modal-body">

        <div class="mb-3">
            @Html.LabelFor(x => x.Name, new {htmlAttributes = new {@class = "form-label"}})
            @Html.EditorFor(x => x.Name, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(x => x.Name)

        </div>
        <div class="mb-3">
            <label for="Description" class="form-label">Description</label>
            <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
        </div>

        <div class="mb-3">
            <label for="CompletionDate">CompletionDate</label>
            <input id="CompletionDate" class="form-control" type="date" name="CompletionDate" value="@Model.CompletionDate?.ToString("yyyy-MM-dd")"/>
            <span id="CompletionDateSelected"></span>

        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Get", "ToDoList", new {listId = Model.ToDoListId})'">Back</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
}

todo-aspnetmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="@Url.Action("Index", "ToDoList")">ToDoList</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "ToDoList", new {isHidden = true})">Show hidden List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="@Url.Action("Edit", "ToDoList")">Add list</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="row">
    @RenderBody()
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

todo-aspnetmvc/Views/ToDoList/Edit.cshtml
@model todo_domain_entities.Models.ToDoListModel

@{
    @if (@Model.Id == Guid.Empty)
    {
        ViewBag.Title = "Add list";}
    else
    {
        ViewBag.Title = "Edit list";}
   
    Layout = "_Layout";
}

@using (Html.BeginForm("Save", "ToDoList", FormMethod.Post))
{
    <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">
    <div class="modal-body">

        <div class="mb-3">
            @Html.LabelFor(x => x.Name, new {htmlAttributes = new {@class = "form-label"}})
            @Html.EditorFor(x => x.Name, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="mb-3">
            <label for="chooseIcon" class="form-label">Icon</label>
            <select class="form-select" aria-label="Default select example" id="chooseIcon" name="Icon">
                <option value="img/no-pictures.png">no picture</option>
                <option value="img/calendar.png">calendar</option>
                <option value="img/person.png">person</option>
                <option value="img/today.png">today</option>
            </select>

        </div>
        <div class="mb-3">
            <label>Hidden</label>
            @Html.CheckBox("IsHidden", @Model.IsHidden)
        </div>
    </div>
    <div class="modal-footer">
        @if (@Model.Id == Guid.Empty)
        {
            <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Index", "ToDoList")'">Back</button>
        }
        else
        {
            <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("Get", "ToDoList", new {listId = @Model.Id})'">Back</button>
        }
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
}

todo-aspnetmvc/Views/ToDoList/Get.cshtml
@using todo_domain_entities.Models
@model todo_domain_entities.Models.ToDoListModel

@{
    ViewBag.Title = "List";
    Layout = "_Layout";
}

<div class="card" style="width: 30rem;">
    <ul class="list-group list-group-flush">
        <div class="btn-group" role="group" aria-label="Basic example">
            @using (Html.BeginForm("DeleteList", "ToDoList", new {listId = Model.Id}))
            {
                <button type="submit" name="X-HTTP-Method-Override" value="DELETE" class="btn btn-outline-primary" formnovalidate
                        class="cancel" onclick="return confirm('Are you sure?')">
                    Delete
                </button>
            }
            <button type="submit" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Edit", "ToDoList", new {listId = Model.Id})'">Edit list</button>
        </div>

    </ul>

    <div class="card-header">
        <img src=@Model.Icon alt="..." class="img-circle">
        @Model.Name
    </div>

    <ol class="list-group list-group">
        @foreach (var i in Model.Items)
        {
            <li class="list-group-item d-flex justify-content-between align-items-start ">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">
                        <input id="cb-@i.Id" task-id="@i.Id" list-id="@i.ToDoList" class="form-check-input me-1 task-item" type="checkbox" @(i.Status == StatusItem.Completed ? "checked" : "")>

                        @i.Name
                    </div>
                    <div class="fw-gray">
                        @(i.CompletionDate != null ? "Completion date:" : "")
                        @i.CompletionDate?.ToString("dd.MM.yyyy")
                    </div>
                </div>
                <ul class="ul-w">
                    <li>
                        <button onclick="location.href='@Url.Action("EditItem", "Items", new {taskId = i.Id})'" class="badge bg-primary rounded-pill task-button">Edit</button>
                    </li>
                    <li>
                        @using (Html.BeginForm("DeleteTask", "Items", new {taskId = @i.Id}, FormMethod.Post))
                        {
                            <button type="submit" name="X-HTTP-Method-Override" value="DELETE" class="badge bg-primary rounded-pill task-button" formnovalidate
                                    class="cancel" onclick="return confirm('Are you sure?')">
                                Delete
                            </button>
                        }
                    </li>
                </ul>
            </li>
        }

        <div class="btn-group" role="group" aria-label="Basic example">
            <button onclick="location.href='@Url.Action("EditItem", "Items", new {listId = Model.Id})'" class="btn btn-outline-primary" type="button">Add task</button>
        </div>
    </ol>
</div>



@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
    $(document).on("click", ".task-item", function(){
        var status = $(this).is(':checked') ? 1 : 0;
        var id = $(this).attr("task-id");
        var listId = $(this).attr("list-id");
        $.post("/Items/UpdateStatus/"+id, {status: status,ToDoListId: listId }, function (json) {
        });
    });
    </script>


}

todo-aspnetmvc/Views/ToDoList/Index.cshtml
@model List<todo_domain_entities.Models.ToDoListModel>

@{
        ViewBag.Title = "Lists";
        Layout = "_Layout";
}

<div class="lists-container">
    <div class="lists">
            @foreach (var p in Model)
            {
                <div class="todo-list" onclick="location.href='@Url.Action("Get", "ToDoList", new { listId = p.Id })'">
                    <div class="list-icon">
                        @if(!string.IsNullOrEmpty(p.Icon))
                        {
                        <img src=@p.Icon alt="..." class="img-circle">
                        }
                        else
                        {
                            <img src="img/no-pictures.png" alt="no picture" class="img-circle">
                        }
                   </div>
                    <div class="list-info">
                        <div class="list-head">
                            @p.Name
                        </div>
                        <div class="list-items-count">
                            @p.Items.Count tasks
                        </div>
                    </div>
                </div>
            }
    </div>
</div>

todo-aspnetmvc/Views/ToDoList/WithItems.cshtml
@model List<todo_domain_entities.Models.ToDoListModel>


<div class="lists-container">
    <div class="lists">
        @foreach (var p in Model)
        {
            <div class="todo-list">
                <div class="list-icon">
                    @if (!string.IsNullOrEmpty(p.Icon))
                    {
                        <img src=@p.Icon alt="..." class="img-circle">
                    }
                    else
                    {
                        <img src="img/no-pictures.png" alt="no picture" class="img-circle">
                    }
                </div>

                <div class="list-info">
                    <div class="list-head">
                        @p.Name
                    </div>

                    @foreach (var i in p.Items)
                    {
                        <div class="list-group">
                            <label class="list-group-item">
                                <input class="form-check-input me-1" type="checkbox" value="Name">
                                @i.Name
                            </label>
                        </div>
                    }
                </div>
            </div>
        }
    </div>

</div>